# Generated by Django 6.0.5 on 2026-06-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0003_add_address_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_status', 'order_status')], default='order_status', max_length=20)),
                ('order_status', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.storeuser')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-created_at'],
            },
        ),
    ]
