# Generated by Django 6.0.5 on 2026-06-20 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_add_delivery_range_fields'),
        ('orders', '0001_initial'),
        ('products', '0002_add_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_quantity', models.IntegerField()),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('reason', models.CharField(choices=[('order_deduct', '下单扣减'), ('merchant_adjust', '商家调整'), ('batch_toggle', '批量上下架'), ('order_cancel', '取消订单返还')], max_length=30)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('operator_role', models.CharField(blank=True, default='', max_length=20)),
                ('operator_name', models.CharField(blank=True, default='', max_length=100)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledgers', to='merchants.merchant')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledgers', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledgers', to='products.product')),
            ],
            options={
                'db_table': 'stock_ledger',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product_id', '-created_at'], name='stock_ledge_product_236a52_idx'), models.Index(fields=['merchant_id', '-created_at'], name='stock_ledge_merchan_7d16aa_idx'), models.Index(fields=['reason'], name='stock_ledge_reason_02f4c4_idx')],
            },
        ),
    ]
