# Generated by Django 5.1.6

from django.db import migrations, models


DEFAULT_BUSINESS_HOURS = {
    '0': {'enabled': True, 'start': '08:00', 'end': '22:00'},
    '1': {'enabled': True, 'start': '08:00', 'end': '22:00'},
    '2': {'enabled': True, 'start': '08:00', 'end': '22:00'},
    '3': {'enabled': True, 'start': '08:00', 'end': '22:00'},
    '4': {'enabled': True, 'start': '08:00', 'end': '22:00'},
    '5': {'enabled': True, 'start': '08:00', 'end': '22:00'},
    '6': {'enabled': True, 'start': '08:00', 'end': '22:00'}
}


def set_default_business_hours(apps, schema_editor):
    Merchant = apps.get_model('merchants', 'Merchant')
    Merchant.objects.all().update(business_hours=DEFAULT_BUSINESS_HOURS)


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='business_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(set_default_business_hours),
    ]
