# Generated by Django 6.0.5 on 2026-06-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
